In [1]:
import numpy as np

def levenshtein(seq1, seq2):
    size_x = len(seq1) + 1
    size_y = len(seq2) + 1
    matrix = np.zeros ((size_x, size_y))
    for x in range(size_x):
        matrix [x, 0] = x
    for y in range(size_y):
        matrix [0, y] = y

    for x in range(1, size_x):
        for y in range(1, size_y):
            if min (seq1[x-1], seq2[y-1])==0:
                 matrix [x,y] = max(seq1[x-1], seq2[y-1])
            
            elif seq1[x-1] == seq2[y-1]:
                matrix [x,y] = min(
                    matrix[x-1, y] + 1,
                    matrix[x-1, y-1],
                    matrix[x, y-1] + 1
                )
            else:
                matrix [x,y] = min(
                    matrix[x-1,y] + 1,
                    matrix[x-1,y-1] + 1,
                    matrix[x,y-1] + 1
                )
    print (matrix)
    return (matrix[size_x - 1, size_y - 1])

In [2]:
print(levenshtein('kitten','sitting'))

[[0. 1. 2. 3. 4. 5. 6. 7.]
 [1. 1. 2. 3. 4. 5. 6. 7.]
 [2. 2. 1. 2. 3. 4. 5. 6.]
 [3. 3. 2. 1. 2. 3. 4. 5.]
 [4. 4. 3. 2. 1. 2. 3. 4.]
 [5. 5. 4. 3. 2. 2. 3. 4.]
 [6. 6. 5. 4. 3. 3. 2. 3.]]
3.0
